apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  labels:
    app: nginx
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: nginx-active
      previewService: nginx-preview
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.24.0
