apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-app
  namespace: argocd
spec:
  destination: 
    namespace: rollout-test 
    server: https://kubernetes.default.svc 
  project: cogsre
  source:
    path: ./resources/child
    repoURL: https://github.com/david-curran-90/argocd-rollouts-learning.git
    targetRevision: main
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: argoproj.io
    kind: Rollout
    jsonPointers:
    - /spec/replicas
