apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-test
  namespace: argocd
spec:
  destination: 
    namespace: rollout-test 
    server: https://kubernetes.default.svc 
  project: default
  source:
    path: ./
    repoURL: https://github.com/david-curran-90/argocd-rollouts-learning.git
    targetRevision: main
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
